from django.urls import path

from .views import (
    attendance_list, available_time_slots, check_in, class_occurrences,
    classes, confirm, create_student, delete_class, delete_occurrence,
    delete_payment, delete_schedule, delete_school, delete_student, edit_class,
    edit_occurrence, edit_price, edit_school, edit_student,
    get_attended_students, get_user, payment_summary, payments,
    prices, schedules, school_detail, schools, students_view,
    today_class_occurrences, today_classes_list, create_invitation,
    accept_invitation, list_memberships, edit_membership, delete_membership,
    available_occurrence_time,
)

urlpatterns = [
    path("check_in/", check_in, name="check_in"),
    path("confirm/", confirm, name="confirm"),
    path("attendances/", attendance_list, name="attendances"),
    path("classes/", classes, name="classes"),
    path("today_classes_list/", today_classes_list, name="today_classes_list"),
    path("today_class_occurrences/", today_class_occurrences, name="today_class_occurrences"),
    path("class_occurrences/", class_occurrences, name="class_occurrences"),
    path("class_occurrences/<int:occurrence_id>/delete/", delete_occurrence, name="delete_occurrence"),
    path("class_occurrences/<int:occurrence_id>/edit/", edit_occurrence, name="edit_occurrence"),
    path("classes/<int:class_id>/edit/", edit_class, name="edit_class"),
    path("classes/<int:class_id>/delete/", delete_class, name="delete_class"),
    path("students/", students_view, name="students"),
    path("students/<int:student_id>/edit/", edit_student, name="edit_student"),
    path("students/<int:student_id>/delete/", delete_student, name="delete_student"),
    path("attended_students/", get_attended_students, name="attended_students"),
    path("prices/", prices, name="prices"),
    path("prices/<int:price_id>/", edit_price, name="edit_price"),
    path("payments/", payments, name="payments"),
    path("payments/<int:payment_id>/delete/", delete_payment, name="delete_payment"),
    path("payment_summary/", payment_summary, name="payment_summary"),
    path("schedules/", schedules, name="schedules"),
    path("schedules/<int:schedule_id>/delete/", delete_schedule, name="delete_schedule"),
    path("available_time_slots/", available_time_slots, name="available_time_slots"),
    path("available_occurrence_time/", available_occurrence_time, name="available_occurrence_time"),
    path("me/", get_user, name="get_user"),
    path("schools/", schools, name="schools"),
    path("schools/<int:school_id>/", school_detail, name="school_detail"),
    path("schools/<int:school_id>/edit/", edit_school, name="edit_school"),
    path("schools/<int:school_id>/delete/", delete_school, name="delete_school"),
    path("invitations/", create_invitation, name="create_invitation"),
    path("invitations/<int:invitation_id>/accept/", accept_invitation, name="accept_invitation"),
    path("memberships/", list_memberships, name="list_memberships"),
    path("memberships/<int:membership_id>/edit/", edit_membership, name="edit_membership"),
    path("memberships/<int:membership_id>/delete/", delete_membership, name="delete_membership"),
]
