# Generated by Django 5.1.6 on 2025-11-25 23:50

import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('is_recurring', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyPaymentsSummary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('summary_date', models.DateField(help_text='Only the month and year are meaningful. Day will always be set to 1.')),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('is_liability_form_sent', models.BooleanField(default=False)),
                ('emergency_contacts', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('clerk_user_id', models.CharField(max_length=255, unique=True)),
                ('role', models.CharField(choices=[('teacher', 'Teacher'), ('admin', 'Administrator'), ('owner', 'Owner')], default='teacher', max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_time', models.TimeField()),
                ('class_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.classmodel')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.day')),
            ],
            options={
                'unique_together': {('day', 'class_time')},
            },
        ),
        migrations.CreateModel(
            name='ClassOccurrence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fallback_class_name', models.CharField(blank=True, max_length=100)),
                ('planned_date', models.DateField()),
                ('actual_date', models.DateField()),
                ('planned_start_time', models.TimeField()),
                ('actual_start_time', models.TimeField()),
                ('planned_duration', models.PositiveIntegerField()),
                ('actual_duration', models.PositiveIntegerField()),
                ('is_cancelled', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('class_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.classmodel')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.schedule')),
            ],
            options={
                'unique_together': {('fallback_class_name', 'actual_date', 'actual_start_time')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(blank=True, max_length=50)),
                ('class_name', models.CharField(blank=True, max_length=50)),
                ('amount', models.FloatField()),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_month', models.IntegerField()),
                ('payment_year', models.IntegerField()),
                ('class_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.classmodel')),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.student')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.classmodel')),
            ],
            options={
                'unique_together': {('class_id',)},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fallback_class_id', models.IntegerField(blank=True, null=True)),
                ('fallback_student_id', models.IntegerField(blank=True, null=True)),
                ('student_first_name', models.CharField(blank=True, max_length=50)),
                ('student_last_name', models.CharField(blank=True, max_length=50)),
                ('class_name', models.CharField(blank=True, max_length=50)),
                ('attendance_date', models.DateField(default=datetime.date.today)),
                ('is_showed_up', models.BooleanField(default=True)),
                ('class_occurrence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.classoccurrence')),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.student')),
            ],
            options={
                'unique_together': {('student_id', 'class_occurrence')},
            },
        ),
    ]
