# Generated by Django 5.1.6 on 2026-01-08 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('kiosk', 'Kiosk'), ('teacher', 'Teacher'), ('admin', 'Administrator'), ('owner', 'Owner')], default='teacher', max_length=50),
        ),
    ]
