# Generated by Django 5.1.6 on 2025-03-12 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rename_firstname_student_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classmodel',
            old_name='class_id',
            new_name='id',
        ),
    ]
