# Generated by Django 5.1.6 on 2026-02-05 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_user_clerk_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('clerk_org_id', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('logo_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('kiosk', 'Kiosk'), ('teacher', 'Teacher'), ('admin', 'Administrator'), ('owner', 'Owner')], default='teacher', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AlterField(
            model_name='classmodel',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='classoccurrence',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='price',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendance',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.school'),
        ),
        migrations.AddField(
            model_name='classmodel',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.school'),
        ),
        migrations.AddField(
            model_name='classoccurrence',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.school'),
        ),
        migrations.AddField(
            model_name='monthlypaymentssummary',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.school'),
        ),
        migrations.AddField(
            model_name='payment',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.school'),
        ),
        migrations.AddField(
            model_name='price',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.school'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.school'),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.school'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('school', 'student_id', 'class_occurrence')},
        ),
        migrations.AlterUniqueTogether(
            name='classmodel',
            unique_together={('school', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='classoccurrence',
            unique_together={('school', 'fallback_class_name', 'actual_date', 'actual_start_time')},
        ),
        migrations.AlterUniqueTogether(
            name='monthlypaymentssummary',
            unique_together={('school', 'summary_date')},
        ),
        migrations.AlterUniqueTogether(
            name='price',
            unique_together={('school', 'class_id')},
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('school', 'day', 'class_time')},
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('school', 'first_name', 'last_name')},
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['school'], name='backend_att_school__804241_idx'),
        ),
        migrations.AddIndex(
            model_name='classmodel',
            index=models.Index(fields=['school'], name='backend_cla_school__0a8719_idx'),
        ),
        migrations.AddIndex(
            model_name='classoccurrence',
            index=models.Index(fields=['school'], name='backend_cla_school__fcd81a_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlypaymentssummary',
            index=models.Index(fields=['school'], name='backend_mon_school__9a4d03_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['school'], name='backend_pay_school__54619c_idx'),
        ),
        migrations.AddIndex(
            model_name='price',
            index=models.Index(fields=['school'], name='backend_pri_school__16d45b_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['school'], name='backend_sch_school__cde4ef_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school'], name='backend_stu_school__3365e4_idx'),
        ),
        migrations.AddField(
            model_name='schoolmembership',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.school'),
        ),
        migrations.AddField(
            model_name='schoolmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='schoolmembership',
            unique_together={('user', 'school')},
        ),
    ]
