# Generated by Django 5.1.6 on 2026-02-05 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_school_schoolmembership_remove_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.school'),
        ),
        migrations.AlterField(
            model_name='classmodel',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.school'),
        ),
        migrations.AlterField(
            model_name='classoccurrence',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.school'),
        ),
        migrations.AlterField(
            model_name='monthlypaymentssummary',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.school'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.school'),
        ),
        migrations.AlterField(
            model_name='price',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.school'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.school'),
        ),
        migrations.AlterField(
            model_name='schoolmembership',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.school'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.school'),
        ),
    ]
