# Generated by Django 5.1.6 on 2025-03-13 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_rename_student_id_student_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='attendance_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='payments',
            old_name='payment_id',
            new_name='id',
        ),
    ]
