# Generated by Django 5.1.6 on 2026-06-23 01:39

from django.db import migrations

DAYS = [
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
    "Sunday",
]


def populate_days(apps, schema_editor):
    Day = apps.get_model("backend", "Day")
    for name in DAYS:
        Day.objects.get_or_create(name=name)


def remove_days(apps, schema_editor):
    Day = apps.get_model("backend", "Day")
    Day.objects.filter(name__in=DAYS).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_invitation_model'),
    ]

    operations = [
        migrations.RunPython(populate_days, remove_days),
    ]
