# Generated by Django 5.1.6 on 2025-06-02 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_attendance_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyPaymentsSummary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('summary_date', models.DateField(help_text='Only the month and year are meaningful. Day will always be set to 1.')),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.classmodel')),
            ],
        ),
    ]
