# Generated by Django 5.1.6 on 2026-08-27 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_populate_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='timezone',
            field=models.CharField(default='America/Los_Angeles', max_length=64),
        ),
    ]
