# Generated by Django 5.1.6 on 2025-06-02 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_monthlypaymentssummary_prices'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payments',
            new_name='Payment',
        ),
        migrations.RenameModel(
            old_name='Prices',
            new_name='Price',
        ),
    ]
