# Generated by Django 5.1.6 on 2025-06-03 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_rename_payments_payment_rename_prices_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='class_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='class_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='student_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='class_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.classmodel'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.student'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='class_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.classmodel'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='student_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.student'),
        ),
    ]
