# Generated by Django 5.1.6 on 2025-06-18 00:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_attendance_class_name_attendance_student_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
