# Generated by Django 5.1.6 on 2025-07-12 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_alter_payment_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_month',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_year',
            field=models.IntegerField(null=True),
        ),
    ]
