# Generated by Django 5.1.6 on 2025-07-12 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_payment_payment_month_payment_payment_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_year',
            field=models.IntegerField(),
        ),
    ]
