# Generated by Django 5.1.6 on 2025-08-04 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_alter_payment_payment_month_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('day', 'class_time')},
        ),
    ]
