# Generated by Django 5.1.6 on 2025-09-09 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_alter_schedule_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='student_name',
            new_name='student_first_name',
        ),
        migrations.AddField(
            model_name='attendance',
            name='student_last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
