# Generated by Django 5.1.6 on 2025-09-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_rename_student_name_attendance_student_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='fallback_class_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='fallback_student_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
