# Generated by Django 5.1.6 on 2025-09-16 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_attendance_fallback_class_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='emergency_contacts',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='is_liability_form_sent',
            field=models.BooleanField(default=False),
        ),
    ]
