# Generated by Django 5.1.6 on 2025-09-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_student_emergency_contacts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classmodel',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
