# Generated by Django 5.1.6 on 2025-10-07 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_classmodel_duration_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassOccurrence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fallback_class_name', models.CharField(blank=True, max_length=100)),
                ('planned_date', models.DateField()),
                ('actual_date', models.DateField()),
                ('planned_start_time', models.TimeField()),
                ('actual_start_time', models.TimeField()),
                ('planned_duration', models.PositiveIntegerField()),
                ('actual_duration', models.PositiveIntegerField()),
                ('is_cancelled', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('class_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.classmodel')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.schedule')),
            ],
            options={
                'unique_together': {('fallback_class_name', 'actual_date', 'actual_start_time')},
            },
        ),
    ]
