# Generated by Django 5.1.6 on 2025-10-07 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_classoccurrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='classmodel',
            name='is_recurring',
            field=models.BooleanField(default=True),
        ),
    ]
