# Generated by Django 5.1.6 on 2025-10-08 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_classmodel_is_recurring'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='class_occurrence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.classoccurrence'),
        ),
    ]
