# Generated by Django 5.1.6 on 2025-10-17 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_attendance_class_occurrence'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student_id', 'class_occurrence')},
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='class_id',
        ),
    ]
