# Generated by Django 5.1.6 on 2025-11-14 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_alter_attendance_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='price',
            unique_together={('class_id',)},
        ),
    ]
